### ISSUE TITLE
makeCurrentSymAdjMatrix gives Error in gzfile(file) : invalid 'description' argument

### ISSUE THREAD

**Issue by nishagove** [julipetal/petalNet#6] opened 2017-07-21 08:03 UTC
I'm using makeThresholdTable function to refine thresholds generated by the petal's default function.To be able to get the NetworkStat.txt, the makeCurrentSymAdjMatrix function is an internal component of the makeAdjMatrices function. I'm encountering error as shown below;

> makeCurrentSymAdjMatrix(metric,currentTIndex, thresholds,numEdges)
numeric(0)
Error in gzfile(file) : invalid 'description' argument

metric = "SP"
currentTIndex = 0.858
thresholds = c(0.858, 0.863, 0.872, 0.886, 0.90, 0.910)
numEdges= NULL

Please advise

**Comment by julipetal** [comment] 2017-07-21 22:46
This function is an internal function and should not be used outside of its intended frame. 

Why are you not using either one of the two main functions?
`dataToVNs()` or `createSWSFnetFromFile()`

Duplicate of #3

**Comment by nishagove** [comment] 2017-07-25 08:04
I'm performing threshold refining

**Comment by julipetal** [comment] 2017-07-25 17:22
What are the thresholds petal calculated? Did you obtain a small-world, scale-free network? 

If you kept the MMo file I recommend to do the following:
Note: I am assuming that you used "SP" for your first run and the MMo is based on SP (default measure)

`createSWSFnetFromFile(expMFile="myData.txt", metric="SP", thresholds=c(0.858, 0.863, 0.872, 0.886, 0.90, 0.910), MMoExists=TRUE)`

when you call this function your working directory has to include `myData.txt` and the `MMo_SP.RData` file.

**Comment by nishagove** [comment] 2017-08-07 10:37
Thanks a lot.I manage to finish my work with petal. 
Also have read your thesis. I think the thesis content is more clear.

**Closed as completed** 2017-08-08 18:05 UTC
